// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7mKmHleK8veQAL1f1V988iWp5YaCLNIE',
    appId: '1:112957858051:web:989679f5f1ca52bdb3c936',
    messagingSenderId: '112957858051',
    projectId: 'flutter-test-8c8ce',
    authDomain: 'flutter-test-8c8ce.firebaseapp.com',
    storageBucket: 'flutter-test-8c8ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5BVoHQkL8LZR6oeZz5TLwcgvMRJXENTg',
    appId: '1:112957858051:android:1fe1a7966ef278d5b3c936',
    messagingSenderId: '112957858051',
    projectId: 'flutter-test-8c8ce',
    storageBucket: 'flutter-test-8c8ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJVEcVXKeYZG4joh3qSk1gy1-JXbe5qc',
    appId: '1:112957858051:ios:fcc931482e7bcc0cb3c936',
    messagingSenderId: '112957858051',
    projectId: 'flutter-test-8c8ce',
    storageBucket: 'flutter-test-8c8ce.appspot.com',
    iosBundleId: 'com.example.appUdg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJVEcVXKeYZG4joh3qSk1gy1-JXbe5qc',
    appId: '1:112957858051:ios:c0ed13b80ba3b828b3c936',
    messagingSenderId: '112957858051',
    projectId: 'flutter-test-8c8ce',
    storageBucket: 'flutter-test-8c8ce.appspot.com',
    iosBundleId: 'com.example.appUdg.RunnerTests',
  );
}
